spring.application.name=complaint_management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
0e0b6afc60dd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads/

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB

logging.level.root=INFO
logging.level.com.arul.complaint_management=DEBUG
logging.file.name=logs/complaint_management.log